- name: 关闭firewalld
  service: name=firewalld state=stopped
  notify: 关闭开机启动防火墙firewalld

- name: 关闭NetworkManager
  service: name=NetworkManager state=stopped
  notify: 关闭网络管理工具NetworkManager

- name: 关闭postfix服务
  service: name=postfix state=stopped
  notify: 关闭开机启动postfix服务

- name: 关闭rpcbind服务
  service: name=rpcbind state=stopped
  notify: 关闭开机启动rpcbind服务
  ignore_errors: true

- name: 关闭chronyd服务
  service: name=chronyd state=stopped
  notify: 关闭开机启动chronyd服务
  ignore_errors: true

- name: 停用ipv6
  sysctl: name='net.ipv6.conf.all.disable_ipv6' value=1

- name: 关闭selinux
  selinux: state=disabled
  ignore_errors: true

